/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nobody_dalvikhook_Handler */

#ifndef _Included_com_nobody_dalvikhook_Handler
#define _Included_com_nobody_dalvikhook_Handler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callVoidMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_nobody_dalvikhook_Handler_callVoidMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callBooleanMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nobody_dalvikhook_Handler_callBooleanMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callByteMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)B
 */
JNIEXPORT jbyte JNICALL Java_com_nobody_dalvikhook_Handler_callByteMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callCharacterMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)C
 */
JNIEXPORT jchar JNICALL Java_com_nobody_dalvikhook_Handler_callCharacterMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callShortMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)S
 */
JNIEXPORT jshort JNICALL Java_com_nobody_dalvikhook_Handler_callShortMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callIntMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_nobody_dalvikhook_Handler_callIntMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callLongMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_com_nobody_dalvikhook_Handler_callLongMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callFloatMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)F
 */
JNIEXPORT jfloat JNICALL Java_com_nobody_dalvikhook_Handler_callFloatMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callDoubleMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_nobody_dalvikhook_Handler_callDoubleMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_nobody_dalvikhook_Handler
 * Method:    callObjectMethod
 * Signature: (Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_nobody_dalvikhook_Handler_callObjectMethod
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
