/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nobody_dalvikhook_Hook */

#ifndef _Included_com_nobody_dalvikhook_Hook
#define _Included_com_nobody_dalvikhook_Hook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nobody_dalvikhook_Hook
 * Method:    setHook
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/nobody/dalvikhook/Handler;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nobody_dalvikhook_Hook_setHook
  (JNIEnv *, jclass, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
